name: CI/CT workflow for C# ASP .NET Core service docker image

on:
  workflow_dispatch:

jobs:
  ci-ct-job-for-csharp-asp-net-core-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: CI/CT Action for C# Backend Services
        uses: MGTheTrain/github-actions/.github/actions/ci-ct-action-for-csharp-asp-net-core-services@main
        with:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORGANIZATION_ID: ${{ secrets.SNYK_ORGANIZATION_ID }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }} 
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          SRC_WORKING_DIRECTORY: ./src/HelloWorldService
          TEST_WORKING_DIRECTORY: ./test
